---
swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
  
  version: production
basePath: https://tempest.com.br
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/fakepath_tempest":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - somettext
      operationId: findAccounts
      summary: this is example text
  "/malformed_by_tempest":
    delete:
      parameters:
      - description: |
          <noscript>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - tempest
      operationId: tempest
      summary: tempest
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - tempest
      operationId: some_operation
      summary: this is example text
